CREATE(c:City {name: "Copenhagen", population:"1085000", region:"Hovedstaden"});
CREATE(c:City {name: "Aarhus", population:"237551", region:"Midtjylland"});
CREATE(c:City {name: "Odense", population:"158222", region:"Syddanmark"});
CREATE(c:City {name: "Skalborg", population:"122219", region:"Nordjylland"});
CREATE(c:City {name: "Esbjerg", population:"72205", region:"Syddanmark"});
CREATE(c:City {name: "Vejle", population:"51177", region:"Syddanmark"});
CREATE(c:City {name: "Roskilde", population:"44285", region:"Sjælland"});
CREATE(c:City {name: "Viborg", population:"34831", region:"Midtjylland"});
CREATE(c:City {name: "Svendborg", population:"29180", region:"Syddanmark"});
CREATE(c:City {name: "Hillerød", population:"28313", region:"Hovedstaden"});
CREATE(c:City {name: "Frederikshavn", population:"24103", region:"Nordjylland"});
CREATE(c:City {name: "Borød", population:"7167", region:"Sjælland"});
CREATE(c:City {name: "Nyborg", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Hvidovre", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Horsens", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Kastrup", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Ærøskøbing", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Hobro", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Haderslev", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Højby", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Dragør", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Lemvig", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Nykøbing Falster", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Nykøbing Mors", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Sorø", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Kolding", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Hjørring", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Søborg", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Aalborg", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Kokkedal", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Sønderborg", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Albertslund", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Randers", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Solrød Strand", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Vejen", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Ringe", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Herlev", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Odder", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Næstved", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Kongens Lyngby", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Helsinge", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Skanderborg", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Rødovre", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Frederiksberg", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Helsingør", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Allerød", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Skive", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Glostrup", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Ishøj", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Brøndby", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Frederikssund", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Holbæk", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Rudkøbing", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Kirke Hvalsø", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Tønder", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Haslev", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Holte", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Ikast", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Taastrup", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Rønde", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Rønne", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Støvring", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Vallensbæk Strand", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Bogense", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Vordingborg", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Tranebjerg", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Slagelse", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Aabybro", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Aabenraa", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Varde", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Ringsted", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Byrum", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Ballerup", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Aars", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Ringkøbing", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Hinnerup", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Kerteminde", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Farum", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Greve", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Herning", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Struer", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Grindsted", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Grenaa", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Fredericia", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Store Heddinge", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Hørsholm", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Assens", population:"unknown", region:"Syddanmark"});
CREATE(c:City {name: "Maribo", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Køge", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Frederiksværk", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Stenløse", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Thisted", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Kalundborg", population:"unknown", region:"Sjælland"});
CREATE(c:City {name: "Holstebro", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Charlottenlund", population:"unknown", region:"Hovedstaden"});
CREATE(c:City {name: "Brønderslev", population:"unknown", region:"Nordjylland"});
CREATE(c:City {name: "Silkeborg", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Hedensted", population:"unknown", region:"Midtjylland"});
CREATE(c:City {name: "Middelfart", population:"unknown", region:"Syddanmark"});
MATCH(c:City), (c1:City) WHERE c.name = "Copenhagen" AND c1.name = "Taastrup" CREATE(c)-[:Road{time:29}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Copenhagen" AND c1.name = "Søborg" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Copenhagen" AND c1.name = "Helsingør" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Copenhagen" AND c1.name = "Maribo" CREATE(c)-[:Road{time:170}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Copenhagen" AND c1.name = "Næstved" CREATE(c)-[:Road{time:189}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aarhus" AND c1.name = "Randers" CREATE(c)-[:Road{time:25}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aarhus" AND c1.name = "Struer" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aarhus" AND c1.name = "Skive" CREATE(c)-[:Road{time:38}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aarhus" AND c1.name = "Hobro" CREATE(c)-[:Road{time:128}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aarhus" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:93}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odense" AND c1.name = "Varde" CREATE(c)-[:Road{time:19}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odense" AND c1.name = "Middelfart" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odense" AND c1.name = "Fredericia" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odense" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:127}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odense" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:193}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skalborg" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skalborg" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:74}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skalborg" AND c1.name = "Frederikshavn" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Esbjerg" AND c1.name = "Fredericia" CREATE(c)-[:Road{time:89}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Esbjerg" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Esbjerg" AND c1.name = "Vejen" CREATE(c)-[:Road{time:69}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Esbjerg" AND c1.name = "Skive" CREATE(c)-[:Road{time:111}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Esbjerg" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:97}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejle" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:86}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejle" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:50}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejle" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:76}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejle" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:194}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejle" AND c1.name = "Hedensted" CREATE(c)-[:Road{time:146}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Roskilde" AND c1.name = "Sorø" CREATE(c)-[:Road{time:86}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Roskilde" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Roskilde" AND c1.name = "Haslev" CREATE(c)-[:Road{time:38}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Roskilde" AND c1.name = "Vejle" CREATE(c)-[:Road{time:142}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Roskilde" AND c1.name = "Sønderborg" CREATE(c)-[:Road{time:181}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Viborg" AND c1.name = "Randers" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Viborg" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Viborg" AND c1.name = "Ringkøbing" CREATE(c)-[:Road{time:19}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Viborg" AND c1.name = "Frederikshavn" CREATE(c)-[:Road{time:186}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Viborg" AND c1.name = "Støvring" CREATE(c)-[:Road{time:106}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Svendborg" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:26}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Svendborg" AND c1.name = "Tønder" CREATE(c)-[:Road{time:17}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Svendborg" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:40}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Svendborg" AND c1.name = "Skive" CREATE(c)-[:Road{time:169}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Svendborg" AND c1.name = "Odder" CREATE(c)-[:Road{time:142}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hillerød" AND c1.name = "Frederikssund" CREATE(c)-[:Road{time:49}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hillerød" AND c1.name = "Kongens Lyngby" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hillerød" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:53}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hillerød" AND c1.name = "Haslev" CREATE(c)-[:Road{time:149}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hillerød" AND c1.name = "Næstved" CREATE(c)-[:Road{time:181}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikshavn" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:55}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikshavn" AND c1.name = "Hobro" CREATE(c)-[:Road{time:50}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikshavn" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:30}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Borød" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Borød" AND c1.name = "Maribo" CREATE(c)-[:Road{time:77}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Borød" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:34}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Borød" AND c1.name = "Esbjerg" CREATE(c)-[:Road{time:112}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Borød" AND c1.name = "Grindsted" CREATE(c)-[:Road{time:129}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nyborg" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:79}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nyborg" AND c1.name = "Odense" CREATE(c)-[:Road{time:32}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nyborg" AND c1.name = "Vejle" CREATE(c)-[:Road{time:78}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nyborg" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:164}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nyborg" AND c1.name = "Odder" CREATE(c)-[:Road{time:173}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hvidovre" AND c1.name = "Charlottenlund" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hvidovre" AND c1.name = "Farum" CREATE(c)-[:Road{time:63}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hvidovre" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:51}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hvidovre" AND c1.name = "Greve" CREATE(c)-[:Road{time:116}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hvidovre" AND c1.name = "Køge" CREATE(c)-[:Road{time:139}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Horsens" AND c1.name = "Hedensted" CREATE(c)-[:Road{time:41}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Horsens" AND c1.name = "Ikast" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Horsens" AND c1.name = "Odder" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Horsens" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:117}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Horsens" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:160}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kastrup" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:23}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kastrup" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:36}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kastrup" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kastrup" AND c1.name = "Borød" CREATE(c)-[:Road{time:102}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kastrup" AND c1.name = "Næstved" CREATE(c)-[:Road{time:98}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ærøskøbing" AND c1.name = "Sønderborg" CREATE(c)-[:Road{time:80}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ærøskøbing" AND c1.name = "Vejle" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ærøskøbing" AND c1.name = "Grindsted" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ærøskøbing" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:117}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ærøskøbing" AND c1.name = "Ringkøbing" CREATE(c)-[:Road{time:103}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hobro" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:74}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hobro" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:40}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hobro" AND c1.name = "Frederikshavn" CREATE(c)-[:Road{time:24}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haderslev" AND c1.name = "Svendborg" CREATE(c)-[:Road{time:68}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haderslev" AND c1.name = "Varde" CREATE(c)-[:Road{time:25}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haderslev" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:11}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haderslev" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:167}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haderslev" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:175}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Højby" AND c1.name = "Sorø" CREATE(c)-[:Road{time:32}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Højby" AND c1.name = "Køge" CREATE(c)-[:Road{time:34}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Højby" AND c1.name = "Holbæk" CREATE(c)-[:Road{time:33}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Højby" AND c1.name = "Vejen" CREATE(c)-[:Road{time:141}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Højby" AND c1.name = "Aabenraa" CREATE(c)-[:Road{time:114}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Dragør" AND c1.name = "Farum" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Dragør" AND c1.name = "Taastrup" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Dragør" AND c1.name = "Søborg" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Dragør" AND c1.name = "Nykøbing Falster" CREATE(c)-[:Road{time:127}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Dragør" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:121}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Lemvig" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Lemvig" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Lemvig" AND c1.name = "Struer" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Lemvig" AND c1.name = "Støvring" CREATE(c)-[:Road{time:98}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Lemvig" AND c1.name = "Thisted" CREATE(c)-[:Road{time:120}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Falster" AND c1.name = "Køge" CREATE(c)-[:Road{time:26}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Falster" AND c1.name = "Højby" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Falster" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:59}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Falster" AND c1.name = "Tønder" CREATE(c)-[:Road{time:141}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Falster" AND c1.name = "Odense" CREATE(c)-[:Road{time:162}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Mors" AND c1.name = "Aars" CREATE(c)-[:Road{time:17}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Mors" AND c1.name = "Støvring" CREATE(c)-[:Road{time:86}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Nykøbing Mors" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:42}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sorø" AND c1.name = "Maribo" CREATE(c)-[:Road{time:80}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sorø" AND c1.name = "Haslev" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sorø" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sorø" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:130}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sorø" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:102}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kolding" AND c1.name = "Vejen" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kolding" AND c1.name = "Aabenraa" CREATE(c)-[:Road{time:39}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kolding" AND c1.name = "Varde" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kolding" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:93}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kolding" AND c1.name = "Ikast" CREATE(c)-[:Road{time:185}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hjørring" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:14}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hjørring" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hjørring" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:32}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Søborg" AND c1.name = "Kokkedal" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Søborg" AND c1.name = "Taastrup" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Søborg" AND c1.name = "Copenhagen" CREATE(c)-[:Road{time:17}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Søborg" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:136}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Søborg" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:164}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aalborg" AND c1.name = "Byrum" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aalborg" AND c1.name = "Støvring" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aalborg" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kokkedal" AND c1.name = "Søborg" CREATE(c)-[:Road{time:46}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kokkedal" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kokkedal" AND c1.name = "Frederikssund" CREATE(c)-[:Road{time:24}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kokkedal" AND c1.name = "Sorø" CREATE(c)-[:Road{time:138}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kokkedal" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:170}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sønderborg" AND c1.name = "Varde" CREATE(c)-[:Road{time:78}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sønderborg" AND c1.name = "Svendborg" CREATE(c)-[:Road{time:51}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sønderborg" AND c1.name = "Middelfart" CREATE(c)-[:Road{time:54}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sønderborg" AND c1.name = "Rønde" CREATE(c)-[:Road{time:145}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Sønderborg" AND c1.name = "Silkeborg" CREATE(c)-[:Road{time:129}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Albertslund" AND c1.name = "Allerød" CREATE(c)-[:Road{time:17}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Albertslund" AND c1.name = "Frederikssund" CREATE(c)-[:Road{time:38}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Albertslund" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:68}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Albertslund" AND c1.name = "Nykøbing Falster" CREATE(c)-[:Road{time:106}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Albertslund" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:175}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Randers" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:36}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Randers" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:38}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Randers" AND c1.name = "Silkeborg" CREATE(c)-[:Road{time:78}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Randers" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:159}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Randers" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:167}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Solrød Strand" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:76}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Solrød Strand" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:58}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Solrød Strand" AND c1.name = "Køge" CREATE(c)-[:Road{time:64}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Solrød Strand" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:130}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Solrød Strand" AND c1.name = "Aabenraa" CREATE(c)-[:Road{time:104}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejen" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejen" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:39}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejen" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejen" AND c1.name = "Randers" CREATE(c)-[:Road{time:180}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vejen" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:173}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringe" AND c1.name = "Aabenraa" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringe" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:64}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringe" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:11}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringe" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:148}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringe" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:190}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herlev" AND c1.name = "Helsingør" CREATE(c)-[:Road{time:56}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herlev" AND c1.name = "Rønne" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herlev" AND c1.name = "Hvidovre" CREATE(c)-[:Road{time:39}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herlev" AND c1.name = "Kalundborg" CREATE(c)-[:Road{time:127}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herlev" AND c1.name = "Kalundborg" CREATE(c)-[:Road{time:96}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odder" AND c1.name = "Ikast" CREATE(c)-[:Road{time:44}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odder" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odder" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odder" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:195}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Odder" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:153}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Næstved" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:40}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Næstved" AND c1.name = "Sorø" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Næstved" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:35}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Næstved" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:156}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Næstved" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:133}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kongens Lyngby" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:57}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kongens Lyngby" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:34}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kongens Lyngby" AND c1.name = "Ballerup" CREATE(c)-[:Road{time:80}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kongens Lyngby" AND c1.name = "Holbæk" CREATE(c)-[:Road{time:158}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kongens Lyngby" AND c1.name = "Næstved" CREATE(c)-[:Road{time:109}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsinge" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsinge" AND c1.name = "Hørsholm" CREATE(c)-[:Road{time:50}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsinge" AND c1.name = "Hillerød" CREATE(c)-[:Road{time:19}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsinge" AND c1.name = "Højby" CREATE(c)-[:Road{time:172}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsinge" AND c1.name = "Holbæk" CREATE(c)-[:Road{time:179}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skanderborg" AND c1.name = "Ikast" CREATE(c)-[:Road{time:50}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skanderborg" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:86}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skanderborg" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skanderborg" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:116}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skanderborg" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:150}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rødovre" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:36}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rødovre" AND c1.name = "Copenhagen" CREATE(c)-[:Road{time:18}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rødovre" AND c1.name = "Hillerød" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rødovre" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:91}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rødovre" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:111}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksberg" AND c1.name = "Kongens Lyngby" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksberg" AND c1.name = "Hvidovre" CREATE(c)-[:Road{time:32}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksberg" AND c1.name = "Helsingør" CREATE(c)-[:Road{time:79}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksberg" AND c1.name = "Sorø" CREATE(c)-[:Road{time:149}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksberg" AND c1.name = "Haslev" CREATE(c)-[:Road{time:157}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsingør" AND c1.name = "Kongens Lyngby" CREATE(c)-[:Road{time:39}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsingør" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:81}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsingør" AND c1.name = "Ishøj" CREATE(c)-[:Road{time:82}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsingør" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:160}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Helsingør" AND c1.name = "Nykøbing Falster" CREATE(c)-[:Road{time:130}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Allerød" AND c1.name = "Albertslund" CREATE(c)-[:Road{time:74}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Allerød" AND c1.name = "Charlottenlund" CREATE(c)-[:Road{time:54}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Allerød" AND c1.name = "Herlev" CREATE(c)-[:Road{time:26}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Allerød" AND c1.name = "Haslev" CREATE(c)-[:Road{time:122}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Allerød" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:153}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skive" AND c1.name = "Hedensted" CREATE(c)-[:Road{time:63}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skive" AND c1.name = "Herning" CREATE(c)-[:Road{time:28}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skive" AND c1.name = "Herning" CREATE(c)-[:Road{time:73}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skive" AND c1.name = "Thisted" CREATE(c)-[:Road{time:115}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Skive" AND c1.name = "Aars" CREATE(c)-[:Road{time:124}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Glostrup" AND c1.name = "Herlev" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Glostrup" AND c1.name = "Charlottenlund" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Glostrup" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:37}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Glostrup" AND c1.name = "Borød" CREATE(c)-[:Road{time:102}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Glostrup" AND c1.name = "Næstved" CREATE(c)-[:Road{time:184}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ishøj" AND c1.name = "Copenhagen" CREATE(c)-[:Road{time:73}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ishøj" AND c1.name = "Ballerup" CREATE(c)-[:Road{time:35}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ishøj" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ishøj" AND c1.name = "Haslev" CREATE(c)-[:Road{time:144}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ishøj" AND c1.name = "Kalundborg" CREATE(c)-[:Road{time:159}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brøndby" AND c1.name = "Taastrup" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brøndby" AND c1.name = "Taastrup" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brøndby" AND c1.name = "Rønne" CREATE(c)-[:Road{time:59}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brøndby" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:127}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brøndby" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:105}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikssund" AND c1.name = "Herlev" CREATE(c)-[:Road{time:85}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikssund" AND c1.name = "Rødovre" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikssund" AND c1.name = "Albertslund" CREATE(c)-[:Road{time:54}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikssund" AND c1.name = "Greve" CREATE(c)-[:Road{time:198}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederikssund" AND c1.name = "Næstved" CREATE(c)-[:Road{time:145}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holbæk" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holbæk" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:82}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holbæk" AND c1.name = "Nykøbing Falster" CREATE(c)-[:Road{time:49}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holbæk" AND c1.name = "Vejen" CREATE(c)-[:Road{time:92}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holbæk" AND c1.name = "Vejen" CREATE(c)-[:Road{time:117}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rudkøbing" AND c1.name = "Fredericia" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rudkøbing" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:79}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rudkøbing" AND c1.name = "Tønder" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rudkøbing" AND c1.name = "Skive" CREATE(c)-[:Road{time:91}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rudkøbing" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:138}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kirke Hvalsø" AND c1.name = "Sorø" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kirke Hvalsø" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kirke Hvalsø" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:42}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kirke Hvalsø" AND c1.name = "Tønder" CREATE(c)-[:Road{time:149}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kirke Hvalsø" AND c1.name = "Ringe" CREATE(c)-[:Road{time:160}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tønder" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:28}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tønder" AND c1.name = "Odense" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tønder" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:58}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tønder" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:166}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tønder" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:169}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haslev" AND c1.name = "Greve" CREATE(c)-[:Road{time:72}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haslev" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:14}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haslev" AND c1.name = "Maribo" CREATE(c)-[:Road{time:25}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haslev" AND c1.name = "Bogense" CREATE(c)-[:Road{time:105}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Haslev" AND c1.name = "Fredericia" CREATE(c)-[:Road{time:154}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holte" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:29}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holte" AND c1.name = "Frederiksberg" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holte" AND c1.name = "Hørsholm" CREATE(c)-[:Road{time:81}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holte" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:121}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holte" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:153}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ikast" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:10}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ikast" AND c1.name = "Randers" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ikast" AND c1.name = "Rønde" CREATE(c)-[:Road{time:53}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ikast" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:181}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ikast" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:183}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Taastrup" AND c1.name = "Rødovre" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Taastrup" AND c1.name = "Charlottenlund" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Taastrup" AND c1.name = "Hvidovre" CREATE(c)-[:Road{time:41}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Taastrup" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:182}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Taastrup" AND c1.name = "Køge" CREATE(c)-[:Road{time:148}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønde" AND c1.name = "Holstebro" CREATE(c)-[:Road{time:53}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønde" AND c1.name = "Ikast" CREATE(c)-[:Road{time:56}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønde" AND c1.name = "Silkeborg" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønde" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:173}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønde" AND c1.name = "Brønderslev" CREATE(c)-[:Road{time:113}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønne" AND c1.name = "Kongens Lyngby" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønne" AND c1.name = "Søborg" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønne" AND c1.name = "Albertslund" CREATE(c)-[:Road{time:83}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønne" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:138}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Rønne" AND c1.name = "Sorø" CREATE(c)-[:Road{time:174}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Støvring" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Støvring" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:34}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Støvring" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vallensbæk Strand" AND c1.name = "Allerød" CREATE(c)-[:Road{time:61}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vallensbæk Strand" AND c1.name = "Stenløse" CREATE(c)-[:Road{time:79}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vallensbæk Strand" AND c1.name = "Herlev" CREATE(c)-[:Road{time:57}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vallensbæk Strand" AND c1.name = "Næstved" CREATE(c)-[:Road{time:144}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vallensbæk Strand" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:182}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Bogense" AND c1.name = "Assens" CREATE(c)-[:Road{time:85}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Bogense" AND c1.name = "Tønder" CREATE(c)-[:Road{time:44}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Bogense" AND c1.name = "Varde" CREATE(c)-[:Road{time:29}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Bogense" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:154}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Bogense" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:130}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vordingborg" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:10}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vordingborg" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:77}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vordingborg" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:18}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vordingborg" AND c1.name = "Assens" CREATE(c)-[:Road{time:111}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Vordingborg" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:98}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tranebjerg" AND c1.name = "Ikast" CREATE(c)-[:Road{time:66}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tranebjerg" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tranebjerg" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:35}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tranebjerg" AND c1.name = "Aars" CREATE(c)-[:Road{time:199}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Tranebjerg" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:188}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Slagelse" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Slagelse" AND c1.name = "Køge" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Slagelse" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:85}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Slagelse" AND c1.name = "Vejle" CREATE(c)-[:Road{time:112}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Slagelse" AND c1.name = "Vejle" CREATE(c)-[:Road{time:180}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabybro" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:89}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabybro" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabybro" AND c1.name = "Byrum" CREATE(c)-[:Road{time:49}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabenraa" AND c1.name = "Bogense" CREATE(c)-[:Road{time:80}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabenraa" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:68}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabenraa" AND c1.name = "Varde" CREATE(c)-[:Road{time:89}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabenraa" AND c1.name = "Struer" CREATE(c)-[:Road{time:149}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aabenraa" AND c1.name = "Holstebro" CREATE(c)-[:Road{time:92}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Varde" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Varde" AND c1.name = "Vejle" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Varde" AND c1.name = "Svendborg" CREATE(c)-[:Road{time:34}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Varde" AND c1.name = "Odder" CREATE(c)-[:Road{time:122}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Varde" AND c1.name = "Horsens" CREATE(c)-[:Road{time:136}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringsted" AND c1.name = "Sorø" CREATE(c)-[:Road{time:18}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringsted" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:55}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringsted" AND c1.name = "Borød" CREATE(c)-[:Road{time:38}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringsted" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:145}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringsted" AND c1.name = "Svendborg" CREATE(c)-[:Road{time:143}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Byrum" AND c1.name = "Frederikshavn" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Byrum" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:11}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Byrum" AND c1.name = "Aars" CREATE(c)-[:Road{time:44}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ballerup" AND c1.name = "Frederiksværk" CREATE(c)-[:Road{time:42}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ballerup" AND c1.name = "Holte" CREATE(c)-[:Road{time:68}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ballerup" AND c1.name = "Hørsholm" CREATE(c)-[:Road{time:40}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ballerup" AND c1.name = "Højby" CREATE(c)-[:Road{time:132}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ballerup" AND c1.name = "Maribo" CREATE(c)-[:Road{time:159}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aars" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:84}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aars" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Aars" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:20}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringkøbing" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:18}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringkøbing" AND c1.name = "Skive" CREATE(c)-[:Road{time:78}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringkøbing" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:78}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringkøbing" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:120}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Ringkøbing" AND c1.name = "Frederikshavn" CREATE(c)-[:Road{time:147}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hinnerup" AND c1.name = "Herning" CREATE(c)-[:Road{time:85}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hinnerup" AND c1.name = "Odder" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hinnerup" AND c1.name = "Lemvig" CREATE(c)-[:Road{time:29}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hinnerup" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:166}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hinnerup" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:122}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kerteminde" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:42}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kerteminde" AND c1.name = "Grindsted" CREATE(c)-[:Road{time:47}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kerteminde" AND c1.name = "Rudkøbing" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kerteminde" AND c1.name = "Silkeborg" CREATE(c)-[:Road{time:111}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kerteminde" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:197}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Farum" AND c1.name = "Copenhagen" CREATE(c)-[:Road{time:55}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Farum" AND c1.name = "Kastrup" CREATE(c)-[:Road{time:25}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Farum" AND c1.name = "Hillerød" CREATE(c)-[:Road{time:55}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Farum" AND c1.name = "Vordingborg" CREATE(c)-[:Road{time:139}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Farum" AND c1.name = "Maribo" CREATE(c)-[:Road{time:112}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Greve" AND c1.name = "Vordingborg" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Greve" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Greve" AND c1.name = "Slagelse" CREATE(c)-[:Road{time:46}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Greve" AND c1.name = "Middelfart" CREATE(c)-[:Road{time:196}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Greve" AND c1.name = "Assens" CREATE(c)-[:Road{time:197}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herning" AND c1.name = "Randers" CREATE(c)-[:Road{time:68}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herning" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:64}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herning" AND c1.name = "Ikast" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herning" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:155}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Herning" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:191}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Struer" AND c1.name = "Horsens" CREATE(c)-[:Road{time:49}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Struer" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Struer" AND c1.name = "Hinnerup" CREATE(c)-[:Road{time:40}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Struer" AND c1.name = "Støvring" CREATE(c)-[:Road{time:115}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Struer" AND c1.name = "Byrum" CREATE(c)-[:Road{time:151}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grindsted" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:36}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grindsted" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grindsted" AND c1.name = "Haderslev" CREATE(c)-[:Road{time:44}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grindsted" AND c1.name = "Skive" CREATE(c)-[:Road{time:158}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grindsted" AND c1.name = "Tranebjerg" CREATE(c)-[:Road{time:144}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grenaa" AND c1.name = "Skive" CREATE(c)-[:Road{time:35}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grenaa" AND c1.name = "Ringkøbing" CREATE(c)-[:Road{time:18}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grenaa" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:13}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grenaa" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:141}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Grenaa" AND c1.name = "Hjørring" CREATE(c)-[:Road{time:98}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Fredericia" AND c1.name = "Sønderborg" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Fredericia" AND c1.name = "Assens" CREATE(c)-[:Road{time:21}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Fredericia" AND c1.name = "Grindsted" CREATE(c)-[:Road{time:61}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Fredericia" AND c1.name = "Rønde" CREATE(c)-[:Road{time:144}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Fredericia" AND c1.name = "Horsens" CREATE(c)-[:Road{time:176}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Store Heddinge" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:79}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Store Heddinge" AND c1.name = "Kalundborg" CREATE(c)-[:Road{time:44}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Store Heddinge" AND c1.name = "Kalundborg" CREATE(c)-[:Road{time:53}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Store Heddinge" AND c1.name = "Bogense" CREATE(c)-[:Road{time:169}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Store Heddinge" AND c1.name = "Assens" CREATE(c)-[:Road{time:154}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hørsholm" AND c1.name = "Vallensbæk Strand" CREATE(c)-[:Road{time:71}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hørsholm" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:39}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hørsholm" AND c1.name = "Frederiksberg" CREATE(c)-[:Road{time:11}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hørsholm" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:192}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hørsholm" AND c1.name = "Maribo" CREATE(c)-[:Road{time:118}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Assens" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:64}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Assens" AND c1.name = "Vejle" CREATE(c)-[:Road{time:12}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Assens" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:30}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Assens" AND c1.name = "Horsens" CREATE(c)-[:Road{time:145}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Assens" AND c1.name = "Herning" CREATE(c)-[:Road{time:185}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Maribo" AND c1.name = "Næstved" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Maribo" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:75}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Maribo" AND c1.name = "Ringsted" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Maribo" AND c1.name = "Vejen" CREATE(c)-[:Road{time:107}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Maribo" AND c1.name = "Assens" CREATE(c)-[:Road{time:195}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Køge" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:29}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Køge" AND c1.name = "Borød" CREATE(c)-[:Road{time:48}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Køge" AND c1.name = "Borød" CREATE(c)-[:Road{time:70}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Køge" AND c1.name = "Sønderborg" CREATE(c)-[:Road{time:162}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Køge" AND c1.name = "Ærøskøbing" CREATE(c)-[:Road{time:155}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksværk" AND c1.name = "Herlev" CREATE(c)-[:Road{time:89}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksværk" AND c1.name = "Brøndby" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksværk" AND c1.name = "Kongens Lyngby" CREATE(c)-[:Road{time:85}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksværk" AND c1.name = "Store Heddinge" CREATE(c)-[:Road{time:107}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Frederiksværk" AND c1.name = "Kirke Hvalsø" CREATE(c)-[:Road{time:159}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Stenløse" AND c1.name = "Herlev" CREATE(c)-[:Road{time:69}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Stenløse" AND c1.name = "Ballerup" CREATE(c)-[:Road{time:49}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Stenløse" AND c1.name = "Glostrup" CREATE(c)-[:Road{time:23}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Stenløse" AND c1.name = "Højby" CREATE(c)-[:Road{time:94}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Stenløse" AND c1.name = "Borød" CREATE(c)-[:Road{time:178}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Thisted" AND c1.name = "Byrum" CREATE(c)-[:Road{time:45}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Thisted" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:60}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Thisted" AND c1.name = "Hobro" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kalundborg" AND c1.name = "Vordingborg" CREATE(c)-[:Road{time:19}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kalundborg" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:57}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kalundborg" AND c1.name = "Roskilde" CREATE(c)-[:Road{time:73}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kalundborg" AND c1.name = "Odense" CREATE(c)-[:Road{time:154}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Kalundborg" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:182}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holstebro" AND c1.name = "Grenaa" CREATE(c)-[:Road{time:57}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holstebro" AND c1.name = "Struer" CREATE(c)-[:Road{time:15}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holstebro" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:65}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holstebro" AND c1.name = "Nykøbing Mors" CREATE(c)-[:Road{time:134}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Holstebro" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:191}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Charlottenlund" AND c1.name = "Allerød" CREATE(c)-[:Road{time:52}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Charlottenlund" AND c1.name = "Holte" CREATE(c)-[:Road{time:86}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Charlottenlund" AND c1.name = "Farum" CREATE(c)-[:Road{time:62}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Charlottenlund" AND c1.name = "Solrød Strand" CREATE(c)-[:Road{time:132}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Charlottenlund" AND c1.name = "Højby" CREATE(c)-[:Road{time:124}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brønderslev" AND c1.name = "Skalborg" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brønderslev" AND c1.name = "Hobro" CREATE(c)-[:Road{time:30}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Brønderslev" AND c1.name = "Støvring" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Silkeborg" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:67}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Silkeborg" AND c1.name = "Struer" CREATE(c)-[:Road{time:27}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Silkeborg" AND c1.name = "Aarhus" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Silkeborg" AND c1.name = "Aalborg" CREATE(c)-[:Road{time:169}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Silkeborg" AND c1.name = "Aabybro" CREATE(c)-[:Road{time:98}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hedensted" AND c1.name = "Herning" CREATE(c)-[:Road{time:25}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hedensted" AND c1.name = "Skanderborg" CREATE(c)-[:Road{time:88}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hedensted" AND c1.name = "Ikast" CREATE(c)-[:Road{time:23}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hedensted" AND c1.name = "Hobro" CREATE(c)-[:Road{time:164}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Hedensted" AND c1.name = "Støvring" CREATE(c)-[:Road{time:180}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Middelfart" AND c1.name = "Nyborg" CREATE(c)-[:Road{time:30}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Middelfart" AND c1.name = "Kerteminde" CREATE(c)-[:Road{time:16}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Middelfart" AND c1.name = "Odense" CREATE(c)-[:Road{time:57}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Middelfart" AND c1.name = "Odder" CREATE(c)-[:Road{time:102}]->(c1);
MATCH(c:City), (c1:City) WHERE c.name = "Middelfart" AND c1.name = "Herning" CREATE(c)-[:Road{time:141}]->(c1);
